# Branding
logo:         "maher.png"

# Banners
banners:
  landing:    "geo.jpg"


# Site settings
title:        "Maher | Technology for Humans"
subtitle:     "Technology for Humans"
email:        "info@maher.pk"

# Build settings
markdown: kramdown
